# Generated by Django 3.0 on 2019-12-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191211_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='book_title',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
